#!/usr/bin/env node
/* SYNELIGHT — build-sitemap.js
   Generates sitemap.xml and robots.txt from SITE_URL.
   Run: node scripts/build-sitemap.js
   Or:  SITE_URL=https://mysite.com node scripts/build-sitemap.js

   Staging detection:
   - If SITE_URL contains "onrender.com" or is empty → staging mode (noindex)
   - If SITE_URL is a real domain → production mode */
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const rawUrl = (process.env.SITE_URL || "").replace(/\/+$/, "");
const isStaging = !rawUrl || /onrender\.com$|localhost/i.test(rawUrl);
const SITE_URL = rawUrl || "https://synelight-agency.onrender.com";

const PAGES = [
  { loc: "/",                          changefreq: "monthly", priority: "1.0" },
  { loc: "/solutions/",                changefreq: "monthly", priority: "0.9" },
  { loc: "/solutions/web-development/",changefreq: "monthly", priority: "0.9" },
  { loc: "/solutions/ai-automation/",  changefreq: "monthly", priority: "0.9" },
  { loc: "/solutions/ai-lead-generation/", changefreq: "monthly", priority: "0.9" },
  { loc: "/solutions/ai-calling-agent/",   changefreq: "monthly", priority: "0.9" },
  { loc: "/solutions/social-media-management/", changefreq: "monthly", priority: "0.8" },
  { loc: "/solutions/complete-growth-system/",  changefreq: "monthly", priority: "0.9" },
  { loc: "/work/",                     changefreq: "monthly", priority: "0.7" },
  { loc: "/work/ironcore-fitness/",    changefreq: "yearly",  priority: "0.6" },
  { loc: "/process/",                  changefreq: "yearly",  priority: "0.6" },
  { loc: "/about/",                    changefreq: "yearly",  priority: "0.6" },
  { loc: "/insights/",                 changefreq: "weekly",  priority: "0.7" },
  { loc: "/insights/ai-agents-for-business/",         changefreq: "yearly", priority: "0.5" },
  { loc: "/insights/fast-websites-win-customers/",    changefreq: "yearly", priority: "0.5" },
  { loc: "/insights/automated-lead-followup/",        changefreq: "yearly", priority: "0.5" },
  { loc: "/contact/",                  changefreq: "yearly",  priority: "0.9" },
  { loc: "/faq/",                      changefreq: "yearly",  priority: "0.5" }
];

/* ---- sitemap.xml ---- */
const sitemapLines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/build-sitemap.js — do not edit manually -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
];
PAGES.forEach(function (p) {
  sitemapLines.push(
    '  <url><loc>' + SITE_URL + p.loc + '</loc>' +
    '<changefreq>' + p.changefreq + '</changefreq>' +
    '<priority>' + p.priority + '</priority></url>'
  );
});
sitemapLines.push('</urlset>');
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), sitemapLines.join("\n") + "\n", "utf8");
console.log("sitemap.xml → " + PAGES.length + " URLs (" + SITE_URL + ")");

/* ---- robots.txt ---- */
const robotsLines = [
  "# SYNELIGHT - robots.txt",
  "# Generated by scripts/build-sitemap.js"
];

if (isStaging) {
  /* Staging: block all crawlers to prevent indexing the Render URL */
  robotsLines.push(
    "",
    "# STAGING — prevent search engines from indexing this URL",
    "User-agent: *",
    "Disallow: /",
    "",
    "# Production sitemap will be available after custom domain is connected",
    "# Sitemap: https://synelight.com/sitemap.xml"
  );
  console.log("robots.txt → STAGING mode (all crawlers blocked)");
} else {
  robotsLines.push(
    "User-agent: *",
    "Allow: /",
    "Disallow: /admin",
    "Disallow: /api",
    "Disallow: /private",
    "Disallow: /internal",
    "Disallow: /data",
    "Disallow: /lib",
    "",
    "Sitemap: " + SITE_URL + "/sitemap.xml"
  );
  console.log("robots.txt → PRODUCTION mode (sitemap: " + SITE_URL + "/sitemap.xml)");
}

fs.writeFileSync(path.join(ROOT, "robots.txt"), robotsLines.join("\n") + "\n", "utf8");
